/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class ec_app_batch_JavaCallCPlus */

#ifndef _Included_ec_app_batch_JavaCallCPlus
#define _Included_ec_app_batch_JavaCallCPlus
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ec_app_batch_JavaCallCPlus
 * Method:    getobj
 * Signature: (Ljava/lang/String;J)D
 */
JNIEXPORT jdouble JNICALL Java_ec_app_batch_JavaCallCPlus_getobj
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     ec_app_batch_JavaCallCPlus
 * Method:    getsimpleobj
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_ec_app_batch_JavaCallCPlus_getsimpleobj
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ec_app_batch_JavaCallCPlus
 * Method:    getsimpleobjwithseed
 * Signature: (Ljava/lang/String;J)D
 */
JNIEXPORT jdouble JNICALL Java_ec_app_batch_JavaCallCPlus_getsimpleobjwithseed
  (JNIEnv *, jobject, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
